services:
  # app:
  #   container_name: micro_videos_dev-app
  #   build: .
  #   command: bash ./.docker/start.sh
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - .:/home/node/app
        # - '/etc/timezone:/etc/timezone:ro'
        # - '/etc/localtime:/etc/localtime:ro'

  db:
    container_name: micro_videos_dev-db
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined

  rabbitmq:
    container_name: micro_videos_dev-rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin