services:
  app:
    container_name: micro_videos-app
    build: .
    command: bash ./.docker/start.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  db:
    container_name: micro_videos-db
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
