services:
  app:
    container_name: micro_videos_dev-app
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: on-failure
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - ./envs:/home/node/app/envs
    depends_on:
      - db
      - rabbitmq
    environment:
      - GOOGLE_CLOUD_STORAGE_BUCKET
      - GOOGLE_CLOUD_CREDENTIALS

  db:
    container_name: micro_videos_dev-db
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
  
  rabbitmq:
    container_name: micro_videos_dev-rabbitmq
    build: ./.docker/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    tmpfs:
      - /var/lib/rabbitmq